stages:
- build

build:
  stage: build
  variables:
    SIMPATH : "/home/schetinin/fs_inst"
    FAIRROOTPATH : "/home/schetinin/fr_inst"
  script:
    - mkdir build
    - cd build
    - /home/schetinin/fs_inst/bin/cmake ../
    - make
