stages:
- build

build:
  stage: build
  variables:
    SIMPATH : "/home/schetinin/fs_inst"
    FAIRROOTPATH : "/home/schetinin/fr_inst"
    CMAKE : /home/schetinin/fs_inst/bin/cmake
    GO4 : /home/schetinin/go4-5.3.2
    ACCULINA_GO4 : /home/schetinin/accdaq/
    INPUT: /home/schetinin/input
  script:
    - ER=$PWD
    - mkdir $ER/tests
    - echo "================ build ==========================="
    - mkdir $ER/build
    - cd $ER/build
    - $CMAKE ../ -DUSE_DIFFERENT_COMPILER=TRUE
    - make
    - echo "================ build with ACCULINA_GO4 ========="
    - mkdir $ER/build_accdaq
    - cd $ER/build_accdaq
    - $CMAKE ../ -DUSE_DIFFERENT_COMPILER=TRUE -DACCULINNA_GO4=$ACCULINA_GO4/install
    - make
    - echo "================ test EXP1803 ===================="
    - mkdir $ER/tests/EXP1803
    - source $GO4/go4login
    - source $ER/build_accdaq/config.sh
    - cd $ACCULINA_GO4
    - rm -f *.root
    - ${GO4SYS}/bin/go4analysis -v -lib libAccDaqUserAnalysis.so -number 1000 -asf exp1803.lmd.asf.root -file $INPUT/EXP1803/run18_0001.lmd -args exp1803.lmd.root $ER/input/setup2_exp201803.xml
    - mv exp1803.lmd.root $ER/tests/EXP1803/.
    - cd $ER/tests/EXP1803/.
    - root -l -q -b "$ER/macro/EXP1803/beamtime/digibuilder.C(1000,\"exp1803.lmd.root\",\"$ER/input/setup2_exp201803.xml\",\"exp1803.digi.lmd.root\")"
    - root -l -q -b "$ER/macro/EXP1803/sim/exp1803_sim_digi.C(1000,\"exp1803.digi.sim.root\")"
    - root -l -q -b "$ER/macro/EXP1803/sim/exp1803_reco.C(1000,\"exp1803.digi.lmd.root\",\"exp1803.reco.lmd.root\")"
    - root -l -q -b "$ER/macro/EXP1803/sim/exp1803_reco.C(1000,\"exp1803.digi.sim.root\",\"exp1803.reco.sim.root\")"
