stages:
- build

build:
  stage: build
  variables:
    SIMPATH : "/home/schetinin/fs_inst"
    FAIRROOTPATH : "/home/schetinin/fr_inst"
  script:
    - mkdir build
    - cd build
    - /home/schetinin/fs_inst/bin/cmake ../ -DUSE_DIFFERENT_COMPILER=TRUE
    - make
    - cd ../
    - mkdir build_accdaq
    - cd build_accdaq
    - /home/schetinin/fs_inst/bin/cmake ../ -DUSE_DIFFERENT_COMPILER=TRUE -DACCULINNA_GO4=/home/schetinin/accdaq/install
    - make
    
