on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: init step
      uses: ./ # Uses an action in the root directory
      with:
        args: /bin/bash -c "source /opt/er/build/config.sh"
