on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      run: docker build - --build-arg ER=dev -t er < Dockerfile
    - name: init
      run: docker run er /bin/bash -c '/opt/er/build/config.sh'

