on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: build
      run: docker build - --build-arg ER=$GITHUB_SHA -t er < Dockerfile
    - name: init
      run: docker run er /bin/bash -c 'source /opt/er/build/config.sh'

