on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hello world action step
      uses: ./ # Uses an action in the root directory
      id: hello
      with:
        args: echo "Hello"
